add_newline = false

[aws]
disabled = true
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[azure]
disabled = true

[[battery.display]]
threshold = 20
style = 'bold red'

[[battery.display]]
threshold = 45
style = 'bold yellow'

[buf]
disabled = true

[bun]
format = '\[[$symbol($version)]($style)\]'
disabled = true

[c]
disabled = true
format = '\[[$symbol($version(-$name))]($style)\]'

[character]
success_symbol = '\[[✓](bold green)\]'
error_symbol = '\[[✗](bold red)\]'

[cmake]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[⏱$duration]($style)\]'
min_time = 15_000
show_milliseconds = true

[cobol]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[conda]
disabled = true
format = '\[[$symbol$environment]($style)\]'

[container]

[crystal]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[daml]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[dart]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[deno]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[directory]
format = '\[[$path]($style)[$read_only]($read_only_style)\]'

[docker_context]
disabled = true
format = '\[[$symbol$context]($style)\]'

[dotnet]
disabled = true
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
disabled = true
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[env_var]
disabled = true

[erlang]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[fennel]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[fill]

[fossil_branch]
disabled = true
format = '\[[$symbol$branch]($style)\]'

[gcloud]
disabled = true
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$branch]($style)\]'
truncation_length = 32

[git_commit]
tag_disabled = false

[git_metrics]
disabled = true

[git_state]

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[gradle]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
disabled = true
format = '\[[$symbol]($style)\]'

[haskell]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[haxe]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
disabled = true
format = '\[[$symbol$branch]($style)\]'

[java]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[julia]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[kotlin]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[localip]

[line_break]
disabled = true

[lua]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
disabled = true
format = '\[[$symbol$project]($style)\]'

[nim]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
disabled = true
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[ocaml]
disabled = true
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[openstack]
disabled = true
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
disabled = true
format = '\[[$symbol]($style)\]'

[package]
disabled = true
format = '\[[$symbol$version]($style)\]'

[perl]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[php]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
disabled = true
format = '\[[$symbol$channel]($style)\]'

[pulumi]
disabled = true
format = '\[[$symbol$stack]($style)\]'

[purescript]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[python]
disabled = true
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
disabled = true
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[ruby]
disabled = true
detect_variables = []
format = '\[[$symbol($version)]($style)\]'

[rust]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[scala]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[shell]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true
format = '\[[$symbol$environment]($style)\]'

[status]
disabled = true

[sudo]
disabled = false
format = '\[[!]($style)\]'
style = 'bold yellow'

[swift]
disabled = true
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[tfw:$workspace]($style)\]'

[time]
disabled = false
format = '\[[$time]($style)\]'
time_range = '22:30:00-07:00:00'

[username]
format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
disabled = false
format = '\[[$symbol($version)]($style)\]'

[zig]
disabled = false
format = '\[[$symbol($version)]($style)\]'
